### ISSUE TITLE
API Credentials

### ISSUE THREAD

**Issue by jjones3286** [devtbit/tg-scrapper#1]
Hi, 

I am having some issues getting started with this script. Can you specify exactly what is needed with regards to the TG APIs? I have tried creating a .env with the credentials and even gone as far as running the tool in a venv and trying to configure my credential;s in there. 

Can you please advise?

**Comment by devtbit** [comment]
You need to setup the credentials with environment variables. If you are on Linux:

```
export API_PHONE_NUMBER=+XXXXXXXXXX
export API_ID=XXXXXXXXXX
export API_HASH=XXXXXXXXXX
```

You can add this lines to a profile file (i.e. telegram.profile) so before you use this tool just do `source telegram.profile` to load those environment variables.

You can verify that the environment variables are set with `echo $API_ID`.

If you are on Windows I believe is something like `$env:API_ID=XXXXXXX` to set your environment variables. Although I have not tested this tool on Windows so be advised it might not work there.
